version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: ecommerce_db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ecommerce_db
      MYSQL_ROOT_PASSWORD: password

    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce_backend
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - mysql

volumes:
  mysql_data:
    name: mysql_data

networks:
  app-network:
    driver: bridge
