version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_db

    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce_backend
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - mysql

volumes:
  mysql_data:
    name: mysql_data

networks:
  app-network:
    driver: bridge
